<?php namespace EntityBase;

/* This file is generated by the framework, do not modify! */

abstract class ArticleRepositoryBase extends \Phlex\RedFox\EntityRepository {

	protected static $__instance = null;

	protected function __construct() {
		$this->database = 'app';
		$this->table = 'article';
	}

	/**
	 * Creates a blank Article
	 * @return \Entity\Article
	 */
	protected function createNewEntity() { return new \Entity\Article($this); }

	/**
	 * Checks if the given object is an Article
	 * @param \Phlex\RedFox\Entity $object
	 * @return bool
	 */
	public function checkInstance($object) { return $object instanceof \Entity\Article; }
}