<?php namespace EntityBase;

/* This file is generated by the framework, do not modify */

/**
 * Class ArticleBase
 * @package Entity\Base
 * @property $author Entity\Article
 */
abstract class ArticleBase extends \Phlex\RedFox\Entity {

	public  $publishDate;
	public  $title;
	public  $lead;
	public  $data;
	public  $type;
	protected $authorId;

	const TYPE_NEWS = 'news';

	/** @return \EntityModel\ArticleModel */
	public function getModel() { return \EntityModel\ArticleModel::instance(); }

	#region Author relation

	protected function getAuthorId() { return $this->authorId; }

	protected function getAuthor() { return \EntityRepository\ArticleRepository::instance()->get( $this->authorId ); }

	protected function setAuthor( \Entity\Article $related ) {
		if( $related instanceof \Entity\Article ) $this->authorId = $related->id;
		else trigger_error( 'Setting related to different entity (Expected: Article)', E_USER_ERROR );
	}

	protected function unsetAuthor() { $this->authorId = null; }

	protected function issetAuthor() { return !($this->authorId == null); }

	#endregion

}