<?php namespace EntityBase;

/* This file is generated by the framework, do not modify! */

/**
 * @property $author \Entity\User
 */
abstract class NewsBase extends \Phlex\RedFox\Entity {

	public $title = NULL;
	public $lead = 'leadtext';
	protected $authorId = NULL;
	public $data = array (
  'key' => 'value',
);
	public $publishDate = 12;
	public $type = 'news';

	const TYPE_NEWS = "news";
	const TYPE_ARTICLE = "article";
	const TYPE_FEATURE = "feature";
	const TYPE_BLOGPOST = "blogpost";

	/** @return \EntityModel\NewsModel */
	public function getModel() { return \EntityModel\NewsModel::instance(); }

	#region author reference

	protected function getAuthorId() { return $this->authorId; }
	protected function getAuthor() { return \EntityRepository\UserRepository::instance()->get( $this->authorId ); }
	protected function setAuthor( \Entity\User $related ) {
		if( $related instanceof \Entity\User ) $this->authorId = $related->id;
		else trigger_error( 'Setting related to different entity (Expected: User)', E_USER_ERROR );
	}
	protected function unsetAuthor() { $this->authorId = null; }
	protected function issetAuthor() { return !($this->authorId == null); }

	#endregion

}