<?php namespace EntityBase;

/* This file is generated by the framework, do not modify! */

abstract class NewsRepositoryBase extends \Phlex\RedFox\EntityRepository {

	protected static $__instance = null;

	protected function __construct() {
		$this->database = 'app';
		$this->table = 'article';
	}

	/**
	 * Creates a blank News
	 * @return \Entity\News
	 */
	protected function createNewEntity() { return new \Entity\News($this); }

	/**
	 * Checks if the given object is an News
	 * @param \Phlex\RedFox\Entity $object
	 * @return bool
	 */
	public function checkInstance($object) { return $object instanceof \Entity\News; }
}