<?php namespace EntityBase;

/* This file is generated by the framework, do not modify! */

abstract class UserRepositoryBase extends \Phlex\RedFox\EntityRepository {

	protected static $__instance = null;

	protected function __construct() {
		$this->database = 'app';
		$this->table = 'user';
	}

	/**
	 * Creates a blank User
	 * @return \Entity\User
	 */
	protected function createNewEntity() { return new \Entity\User($this); }

	/**
	 * Checks if the given object is an User
	 * @param \Phlex\RedFox\Entity $object
	 * @return bool
	 */
	public function checkInstance($object) { return $object instanceof \Entity\User; }
}