<?php namespace EntityBase;

/* This file is generated by the framework, do not modify! */

/**

 */
abstract class UserBase extends \Phlex\RedFox\Entity {

	public $name = NULL;
	public $email = NULL;



	/** @return \EntityModel\UserModel */
	public function getModel() { return \EntityModel\UserModel::instance(); }


}