<?php
/**
 * This file is generated by the framework, do not modify
 */

namespace EntityBase;

use Entity\ArticleModel;
use Phlex\Database\Access;
use Phlex\RedFox\Entity;


/**
 * Class ArticleBase
 * @package Entity\Base
 */

abstract class ArticleBase extends Entity{
	protected $publishDate;
	protected $title;
	public $lead;
	public $data;
	public $authorId;
	public $type;

	/**
	 * @return Access
	 */
	//public function getDBAccess(){ return $this->_repository->getDBAccess(); }
	//TODO: maybe unneccessary method
	
	/**
	 * @return ArticleModel
	 */
	public function getModel(){ return ArticleModel::instance(); }

}