<?php
/**
 * This file is generated by the framework, do not modify
 */

namespace EntityBase;


use Entity\Article;
use Phlex\RedFox\Entity;
use Phlex\RedFox\EntityRepository;
use Phlex\RedFox\Model\Field;


/**
 * Class ArticleRepositoryBase
 *
 * @package Entity\Base
 * @method Article get(int $id)
 */
class ArticleRepositoryBase extends EntityRepository {

	protected static $__instance = null;

	protected function __construct() {
		$this->database = 'app';
		$this->table = 'article';
	}

	/**
	 * Creates a blank entity
	 * @return static
	 */
	protected function createNewEntity() { return new Article($this); }

	/**
	 * Checks if the given object is mathcing the repository Entity
	 * @param Entity $object
	 * @return bool
	 */
	public function checkInstance($object) { return $object instanceof Article; }

}